# Configuration file for gorun
# ----------------------------
# CommandsFolder  - the commands configuration files location
# HostsFile       - the hosts configuration file location
# AuthType        - ssh authentication type; options: password
# SummaryDetails  - command run summary details; options: all, failed-only or passed-only
CommandsFolder: "commands"
HostsFile: "hosts/hosts_docker.yaml"
AuthType: "password"
SummaryDetails: "failed-only"
