- server: "sprint-rtp-cent.cisco.com"
  port: "22"
  user: "root"
  password: "Cisco1@#"
- server: "sprint-rtp-cent2.cisco.com"
  port: "22"
  user: "root"
  password: "Cisco1@#"
- server: "sprint-rtp-cent3.cisco.com"
  port: "22"
  user: "root"
  password: "Cisco1@#"
