- name: "list_files"
  command: "ls"
  parameters:
    - -l
    - -h
  depends: "nobody"
  output:
    raw: "1234567890"
    filter: "..."
    filtered: "123"
    variable: "ls3"
  flow:
    sequential: true
    parallel: false
    selection: "if"
    iteration: "for"
    
- name: "list_processes"
  command: "ps"
  parameters:
    - aux
  depends: "nobody"
  output:
    raw: '1\n\2\n3\n4'
    filter: "."
    filtered: "1"
    variable: "pid1"
  flow:
    sequential: true
    parallel: false
    selection: "if"
    iteration: "for"
